class AddParts < ActiveRecord::Migration
  def self.up
    Part.delete_all()
      Part.new(:number => " 1424  ", :description => "  CONNECTING ROD  ", :weight => 0.8 ).save()
      Part.new(:number => " 1426  ", :description => "  CONNECTING ROD  ", :weight => 2.15  ).save()
      Part.new(:number => " 3012  ", :description => "  HP DELIVERY VALVE ", :weight => 0.7 ).save()
      Part.new(:number => " 3020  ", :description => "  SUCTION VALVE ", :weight => 1.75  ).save()
      Part.new(:number => " 3021  ", :description => "  DELIVERY VALVE  ", :weight => 1.5 ).save()
      Part.new(:number => " 3022  ", :description => "  SUCTION VALVE ", :weight => 1.5 ).save()
      Part.new(:number => " 3023  ", :description => "  DELIVERY VALVE  ", :weight => 1.5 ).save()
      Part.new(:number => " 3029  ", :description => "  SUCTION VALVE ", :weight => 5.5 ).save()
      Part.new(:number => " 3030  ", :description => "  DELIVERY VALVE  ", :weight => 5.5 ).save()
      Part.new(:number => " 3032  ", :description => "  LP COMBINE VALVE  ", :weight => 2.75  ).save()
      Part.new(:number => " 3033  ", :description => "  HP COMBINE VALVE  ", :weight => 1 ).save()
      Part.new(:number => " 3034  ", :description => "  LP COMBINE VALVE  ", :weight => 3.25  ).save()
      Part.new(:number => " 3035  ", :description => "  HP COMBINE VALVE  ", :weight => 0.65  ).save()
      Part.new(:number => " 3049  ", :description => "  HP SUCTION VALVE  ", :weight => 0.7 ).save()
      Part.new(:number => " 3061  ", :description => "  SUCTION SEAT  ", :weight => 0.42  ).save()
      Part.new(:number => " 3069  ", :description => "  SUCTION SEAT  ", :weight => 1 ).save()
      Part.new(:number => " 3087  ", :description => "  CUSHION PLTE  ", :weight => 0.03  ).save()
      Part.new(:number => " 3092  ", :description => "  SPRING PLATE (.8) ", :weight => 0.015 ).save()
      Part.new(:number => " 3112  ", :description => "  VALVE PLATE ", :weight => 0.15  ).save()
      Part.new(:number => " 3265  ", :description => "  SPRING PLATE (1)  ", :weight => 0.45  ).save()
      Part.new(:number => " 3268  ", :description => "  SPRING PLATE (.8) ", :weight => 0.47  ).save()
      Part.new(:number => " 3364  ", :description => "  PISTON  ", :weight => 2 ).save()
      Part.new(:number => " 3634  ", :description => "  INSPECTION GLASS  ", :weight => 0.6 ).save()
      Part.new(:number => " 3771  ", :description => "  PRESSURE GAUGE, HP  ", :weight => 0.5 ).save()
      Part.new(:number => " 3773  ", :description => "  PRESSURE GAUGE, HP  ", :weight => 0.5 ).save()
      Part.new(:number => " 3877  ", :description => "  NEEDLE BEARING  ", :weight => 1.5 ).save()
      Part.new(:number => " 3878  ", :description => "  NEEDLE BEARING  ", :weight => 1.5 ).save()
      Part.new(:number => " 3879  ", :description => "  NEEDLE BEARING  ", :weight => 1.3 ).save()
      Part.new(:number => " 3880  ", :description => "  NEEDLE BEARING  ", :weight => 1.5 ).save()
      Part.new(:number => " 4420  ", :description => "  SAFETY VALVE, HP  ", :weight => 0.2 ).save()
      Part.new(:number => " 4421  ", :description => "  SAFETY VALVE, LP  ", :weight => 0.35  ).save()
  end
  def self.down
    Part.delete_all()
  end
end