class AddPartPrices < ActiveRecord::Migration
  def self.up
    PartPrice.delete_all()
    PartPrice.new(:currency_id =>   2 , :part_id =>   6 , :price =>   137.56  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   7 , :price =>   79  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   8 , :price =>   79  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   9 , :price =>   39  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   10  , :price =>   419.9 , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   11  , :price =>   412 , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   12  , :price =>   263.2 , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   13  , :price =>   108 , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   19  , :price =>   3.72  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   20  , :price =>   3.46  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   21  , :price =>   13.7  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   22  , :price =>   4.7 , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   23  , :price =>   3.64  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   18  , :price =>   34.5  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   17  , :price =>   20.76 , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   3 , :price =>   43  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   16  , :price =>   46.76 , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   5 , :price =>   52.66 , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   32  , :price =>   25  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   33  , :price =>   35  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   27  , :price =>   23  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   29  , :price =>   29  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   28  , :price =>   42  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   4 , :price =>   63  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   31  , :price =>   22  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   30  , :price =>   18  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   26  , :price =>   19  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   25  , :price =>   11  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   24  , :price =>   90  , :customer_id =>   1 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   6 , :price =>   137.56  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   7 , :price =>   79  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   8 , :price =>   79  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   9 , :price =>   39  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   10  , :price =>   419.9 , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   11  , :price =>   412 , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   12  , :price =>   263.2 , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   13  , :price =>   108 , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   19  , :price =>   3.72  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   20  , :price =>   3.46  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   21  , :price =>   13.7  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   22  , :price =>   4.7 , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   23  , :price =>   3.64  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   18  , :price =>   34.5  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   17  , :price =>   20.76 , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   3 , :price =>   43  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   16  , :price =>   46.76 , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   5 , :price =>   52.66 , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   32  , :price =>   25  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   33  , :price =>   35  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   27  , :price =>   23  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   29  , :price =>   29  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   28  , :price =>   42  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   4 , :price =>   63  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   31  , :price =>   22  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   30  , :price =>   18  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   26  , :price =>   19  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   25  , :price =>   11  , :customer_id =>   2 ).save()
    PartPrice.new(:currency_id =>   2 , :part_id =>   24  , :price =>   90  , :customer_id =>   2 ).save()
  end
  def self.down
    PartPrice.delete_all()
  end
end