class InsertPartPrices < ActiveRecord::Migration
  def self.up
    PartPrice.new(:id =>1  ,:make => "SPERRE", :model => "HV2/219", :part_number => "3020", :part_desc => "SUCTION VALVE", :weight => 1.75, :price => 137.56, :currency => "GBP").save()
    PartPrice.new(:id =>2  ,:make => "SPERRE", :model => "HV2/219", :part_number => "3021", :part_desc => "DELIVERY VALVE", :weight => 1.5 , :price => 79, :currency => "GBP").save()
    PartPrice.new(:id =>3  ,:make => "SPERRE", :model => "HV2/220", :part_number => "3022", :part_desc => "SUCTION VALVE ", :weight => 1.5 , :price => 79, :currency => "GBP").save()
    PartPrice.new(:id =>4  ,:make => "SPERRE", :model => "HV2/220", :part_number => "3023", :part_desc => "DELIVERY VALVE", :weight => 1.5 , :price => 39, :currency => "GBP").save()
    PartPrice.new(:id =>5  ,:make => "SPERRE", :model => "HV2/270", :part_number => "3029", :part_desc => "SUCTION VALVE ", :weight => 5.5 , :price => 419.9 , :currency => "GBP").save()
    PartPrice.new(:id =>6  ,:make => "SPERRE", :model => "HV2/270", :part_number => "3030", :part_desc => "DELIVERY VALVE", :weight => 5.5 , :price => 412 , :currency => "GBP").save()
    PartPrice.new(:id =>7  ,:make => "SPERRE", :model => "HL2/160", :part_number => "3032", :part_desc => "LP COMBINE VALVE", :weight => 2.75, :price => 263.2 , :currency => "GBP").save()
    PartPrice.new(:id =>8  ,:make => "SPERRE", :model => "HV1/140", :part_number => "3033", :part_desc => "HP COMBINE VALVE", :weight => 1 , :price => 108 , :currency => "GBP").save()
    PartPrice.new(:id =>9  ,:make => "SPERRE", :model => "HL2/160", :part_number => "3034", :part_desc => "LP COMBINE VALVE", :weight => 3.25, :price => 383 , :currency => "GBP").save()
    PartPrice.new(:id =>10 ,:make => "SPERRE", :model => "HL2/160", :part_number => "3035", :part_desc => "HP COMBINE VALVE", :weight => 0.65, :price => 125.7 , :currency => "GBP").save()
    PartPrice.new(:id =>11 ,:make => "SPERRE", :model => "HV2/200", :part_number => "3087", :part_desc => "CUSHION PLTE", :weight => 0.03, :price => 3.72, :currency => "GBP").save()
    PartPrice.new(:id =>12 ,:make => "SPERRE", :model => "HV2/200", :part_number => "3092", :part_desc => "SPRING PLATE (.8)", :weight => 0.015 , :price => 3.46, :currency => "GBP").save()
    PartPrice.new(:id =>13 ,:make => "SPERRE", :model => "HV2/270", :part_number => "3112", :part_desc => "VALVE PLATE", :weight => 0.15, :price => 13.7, :currency => "GBP").save()
    PartPrice.new(:id =>14 ,:make => "SPERRE", :model => "HV2/219", :part_number => "3265", :part_desc => "SPRING PLATE (1)", :weight => 0.45, :price => 4.7 , :currency => "GBP").save()
    PartPrice.new(:id =>15 ,:make => "SPERRE", :model => "1A", :part_number => "3268", :part_desc => "SPRING PLATE (.8)", :weight => 0.47, :price => 3.64, :currency => "GBP").save()
    PartPrice.new(:id =>16 ,:make => "SPERRE", :model => "HV2/219", :part_number => "3069", :part_desc => "SUCTION SEAT", :weight => 1 , :price => 34.5, :currency => "GBP").save()
    PartPrice.new(:id =>17 ,:make => "SPERRE", :model => "HV2/219", :part_number => "3061", :part_desc => "SUCTION SEAT", :weight => 0.42, :price => 20.76 , :currency => "GBP").save()
    PartPrice.new(:id =>18 ,:make => "SPERRE", :model => "HL2/90", :part_number => "1424", :part_desc => "CONNECTING ROD", :weight => 0.8 , :price => 43, :currency => "GBP").save()
    PartPrice.new(:id =>19 ,:make => "SPERRE", :model => "HV2/219", :part_number => "3700", :part_desc => "VENTILATOR", :weight => 2 , :price => 32, :currency => "GBP").save()
    PartPrice.new(:id =>20 ,:make => "SPERRE", :model => "HV2/219", :part_number => "3049", :part_desc => "HP SUCTION VALVE", :weight => 0.7 , :price => 46.76 , :currency => "GBP").save()
    PartPrice.new(:id =>21 ,:make => "SPERRE", :model => "HV2/219", :part_number => "3012", :part_desc => "HP DELIVERY VALVE ", :weight => 0.7 , :price => 52.66 , :currency => "GBP").save()
    PartPrice.new(:id =>22 ,:make => "SPERRE", :model => "HL2/90", :part_number => "4420", :part_desc => "SAFETY VALVE, HP", :weight => 0.2 , :price => 25, :currency => "GBP").save()
    PartPrice.new(:id =>23 ,:make => "SPERRE", :model => "HL2/90", :part_number => "4421", :part_desc => "SAFETY VALVE, LP", :weight => 0.35, :price => 35, :currency => "GBP").save()
    PartPrice.new(:id =>24 ,:make => "SPERRE", :model => "HL2/90", :part_number => "3773", :part_desc => "PRESSURE GAUGE, HP", :weight => 0.5 , :price => 23, :currency => "GBP").save()
    PartPrice.new(:id =>25 ,:make => "SPERRE", :model => "HL2/90", :part_number => "3878", :part_desc => "NEEDLE BEARING", :weight => 1.5 , :price => 29, :currency => "GBP").save()
    PartPrice.new(:id =>26 ,:make => "SPERRE", :model => "HL2/90", :part_number => "3877", :part_desc => "NEEDLE BEARING", :weight => 1.5 , :price => 42, :currency => "GBP").save()
    PartPrice.new(:id =>27 ,:make => "SPERRE", :model => "HL2/160", :part_number => "1426", :part_desc => "CONNECTING ROD", :weight => 2.15, :price => 63, :currency => "GBP").save()
    PartPrice.new(:id =>28 ,:make => "SPERRE", :model => "HL2/160", :part_number => "3880", :part_desc => "NEEDLE BEARING", :weight => 1.5 , :price => 22, :currency => "GBP").save()
    PartPrice.new(:id =>29 ,:make => "SPERRE", :model => "HL2/160", :part_number => "3879", :part_desc => "NEEDLE BEARING", :weight => 1.3 , :price => 18, :currency => "GBP").save()
    PartPrice.new(:id =>30 ,:make => "SPERRE", :model => "HL2/160", :part_number => "3771", :part_desc => "PRESSURE GAUGE, HP", :weight => 0.5 , :price => 19, :currency => "GBP").save()
    PartPrice.new(:id =>31 ,:make => "SPERRE", :model => "HL2/160", :part_number => "4421", :part_desc => "SAFETY VALVE, LP", :weight => 0.35, :price => 35, :currency => "GBP").save()
    PartPrice.new(:id =>32 ,:make => "SPERRE", :model => "HL2/160", :part_number => "4420", :part_desc => "SAFETY VALVE, HP", :weight => 0.2 , :price => 25, :currency => "GBP").save()
    PartPrice.new(:id =>33 ,:make => "SPERRE", :model => "HL2/77", :part_number => "4421", :part_desc => "SAFETY VALVE, LP", :weight => 0.35, :price => 35, :currency => "GBP").save()
    PartPrice.new(:id =>34 ,:make => "SPERRE", :model => "HL2/77", :part_number => "4420", :part_desc => "SAFETY VALVE, HP", :weight => 0.2 , :price => 25, :currency => "GBP").save()
    PartPrice.new(:id =>35 ,:make => "SPERRE", :model => "HL2/90", :part_number => "4421", :part_desc => "SAFETY VALVE, LP", :weight => 0.35, :price => 35, :currency => "GBP").save()
    PartPrice.new(:id =>36 ,:make => "SPERRE", :model => "HL2/90", :part_number => "4420", :part_desc => "SAFETY VALVE, HP", :weight => 0.2 , :price => 25, :currency => "GBP").save()
    PartPrice.new(:id =>37 ,:make => "SPERRE", :model => "HL2/77", :part_number => "3773", :part_desc => "PRESSURE GAUGE, HP", :weight => 0.5 , :price => 23, :currency => "GBP").save()
    PartPrice.new(:id =>38 ,:make => "SPERRE", :model => "HL2/120", :part_number => "4421", :part_desc => "SAFETY VALVE, LP", :weight => 0.35, :price => 35, :currency => "GBP").save()
    PartPrice.new(:id =>39 ,:make => "SPERRE", :model => "HL2/120", :part_number => "4420", :part_desc => "SAFETY VLAVE, HP", :weight => 0.2 , :price => 25, :currency => "GBP").save()
    PartPrice.new(:id =>40 ,:make => "SPERRE", :model => "HL2/120", :part_number => "3773", :part_desc => "PRESSURE GAUGE, HP", :weight => 0.5 , :price => 23, :currency => "GBP").save()
    PartPrice.new(:id =>41 ,:make => "SPERRE", :model => "HL2/160", :part_number => "3773", :part_desc => "PRESSURE GAUGE, HP", :weight => 0.5 , :price => 23, :currency => "GBP").save()
    PartPrice.new(:id =>42 ,:make => "SPERRE", :model => "HL2/160", :part_number => "3700", :part_desc => "VENTILATOR", :weight => 2 , :price => 32, :currency => "GBP").save()
    PartPrice.new(:id =>43 ,:make => "SPERRE", :model => "HL2/160", :part_number => "3634", :part_desc => "INSPECTION GLASS", :weight => 0.6 , :price => 11, :currency => "GBP").save()
    PartPrice.new(:id =>44 ,:make => "SPERRE", :model => "HL2/160", :part_number => "3364", :part_desc => "PISTON", :weight => 2 , :price => 90, :currency => "GBP").save()
  end
  def self.down
  end
end